spring:
  application:
    name: spring-metrics-workshop

server:
  port: 8080

management:
  metrics:
    export:
      # only for presentation reason
      datadog:
        enabled: false
        application-key: some-app
        api-key: some-api-key
      prometheus:
        enabled: true

  endpoints:
    web:
      exposure:
        include: health, info, loggers, metrics