spring:
  application:
    name: spring-metrics-workshop

server:
  port: 8080

management:
  metrics:
    export:
      datadog:
        enabled: false
      prometheus:
        enabled: false
  endpoints:
    web:
      exposure:
        include: health, info, loggers, metrics